name = "website-builder"
main = ".open-next/worker.js"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
keep_vars = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cache"