import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Terms of Service
          </h1>
          <p className="text-gray-600">Last updated: August 16th, 2025</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Agreement to Terms</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="text-gray-700">
              By accessing and using Builddrr, you accept and agree to be bound
              by the terms and provision of this agreement. If you do not agree
              to abide by the above, please do not use this service.
            </p>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Service Description
              </h2>
              <p className="text-gray-700">
                Builddrr is an AI-powered website building platform that allows
                users to create, customize, and deploy websites through
                conversational AI interactions. Our service includes website
                hosting, domain management, and various tools for website
                creation and maintenance.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                User Accounts
              </h2>
              <div className="space-y-3 text-gray-700">
                <p>To use our service, you must:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Be at least 18 years old or have parental consent</li>
                  <li>
                    Provide accurate and complete registration information
                  </li>
                  <li>Maintain the security of your account credentials</li>
                  <li>
                    Accept responsibility for all activities under your account
                  </li>
                  <li>Notify us immediately of any unauthorized access</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Acceptable Use
              </h2>
              <div className="space-y-3 text-gray-700">
                <p>You agree not to use our service to:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>
                    Create content that is illegal, harmful, or violates others'
                    rights
                  </li>
                  <li>Distribute malware, spam, or malicious code</li>
                  <li>Infringe on intellectual property rights</li>
                  <li>
                    Engage in harassment, abuse, or discriminatory behavior
                  </li>
                  <li>Attempt to gain unauthorized access to our systems</li>
                  <li>Use our service for any unlawful purposes</li>
                  <li>Violate any applicable laws or regulations</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Content Ownership and Rights
              </h2>
              <div className="space-y-3 text-gray-700">
                <h3 className="font-medium">Your Content</h3>
                <p>
                  You retain ownership of all content you create using our
                  platform. You grant us a limited license to host, display, and
                  distribute your content as necessary to provide our services.
                </p>

                <h3 className="font-medium">Our Platform</h3>
                <p>
                  Builddrr and its original content, features, and functionality
                  are owned by us and are protected by international copyright,
                  trademark, and other intellectual property laws.
                </p>

                <h3 className="font-medium">AI-Generated Content</h3>
                <p>
                  Content generated by our AI system is provided to you for your
                  use. However, you are responsible for ensuring that any
                  AI-generated content complies with applicable laws and does
                  not infringe on third-party rights.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Payment and Billing
              </h2>
              <div className="space-y-3 text-gray-700">
                <ul className="list-disc pl-6 space-y-1">
                  <li>
                    Subscription fees are billed in advance on a recurring basis
                  </li>
                  <li>All fees are non-refundable except as required by law</li>
                  <li>We may change our pricing with 14 days notice</li>
                  <li>Failure to pay may result in service suspension</li>
                  <li>
                    You are responsible for all taxes associated with your use
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Service Availability
              </h2>
              <p className="text-gray-700">
                While we strive for high availability, we do not guarantee
                uninterrupted access to our service. We may perform maintenance,
                updates, or experience technical issues that temporarily affect
                service availability. We are not liable for any damages
                resulting from service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Termination
              </h2>
              <div className="space-y-3 text-gray-700">
                <p>Either party may terminate this agreement:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>
                    You may cancel your account at any time through your
                    dashboard
                  </li>
                  <li>
                    We may terminate your account for violations of these terms
                  </li>
                  <li>We may discontinue the service with reasonable notice</li>
                  <li>
                    Upon termination, your right to use the service ceases
                    immediately
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Disclaimers and Limitations
              </h2>
              <div className="space-y-3 text-gray-700">
                <p>
                  Our service is provided "as is" without warranties of any
                  kind. We disclaim all warranties, express or implied,
                  including but not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Merchantability and fitness for a particular purpose</li>
                  <li>Non-infringement of third-party rights</li>
                  <li>Accuracy or reliability of AI-generated content</li>
                  <li>Uninterrupted or error-free operation</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Indemnification
              </h2>
              <p className="text-gray-700">
                You agree to indemnify and hold us harmless from any claims,
                damages, or expenses arising from your use of our service,
                violation of these terms, or infringement of any rights of
                another.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Changes to Terms
              </h2>
              <p className="text-gray-700">
                We reserve the right to modify these terms at any time. We will
                notify users of significant changes via email or platform
                notification. Continued use after changes constitutes acceptance
                of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Governing Law
              </h2>
              <p className="text-gray-700">
                These terms are governed by and construed in accordance with
                applicable laws. Any disputes will be resolved through binding
                arbitration or in courts of competent jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                Contact Information
              </h2>
              <p className="text-gray-700">
                If you have questions about these Terms of Service, please
                contact us:
              </p>
              <ul className="list-none space-y-1 text-gray-700 mt-2">
                <li>Email: savonen.emppu@gmail.com</li>
                <li>
                  <a
                    href="https://discord.gg/Fg8qtgMN"
                    className="text-blue-500 hover:text-blue-600"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Support (Discord)
                  </a>
                </li>
              </ul>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
